version: "3.8"
services:
  bot:
    build: .
    command: "python main.py"
    volumes:
      - .:/code/
  server:
    build: .
    ports:
      - 80:5000
    command: "python server.py"
    volumes:
      - .:/code/
